# Generated by Django 4.2.29 on 2026-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampusEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_meters", models.FloatField()),
                ("is_accessible", models.BooleanField(default=True)),
                ("surface_type", models.CharField(default="asphalt", max_length=50)),
                ("has_ramp", models.BooleanField(default=False)),
                ("slope_grade", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "campus_edges",
            },
        ),
        migrations.CreateModel(
            name="CampusNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("INTERSECTION", "Intersection"),
                            ("GATE", "Gate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_accessible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "campus_nodes",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "start_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("end_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("end_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("waypoints", models.JSONField(blank=True, default=list)),
                ("distance_meters", models.FloatField()),
                ("estimated_time_seconds", models.IntegerField()),
                ("is_accessible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "routes",
            },
        ),
    ]
