# Generated by Django 4.2.29 on 2026-04-02 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campusedge",
            name="from_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_edges",
                to="routing.campusnode",
            ),
        ),
        migrations.AddField(
            model_name="campusedge",
            name="to_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_edges",
                to="routing.campusnode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campusedge",
            unique_together={("from_node", "to_node")},
        ),
    ]
