# Generated by Django 5.2.12 on 2026-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_COMPLETE', 'Registration Complete'), ('REPORT_VERIFIED', 'Report Verified'), ('REPORT_RESOLVED', 'Report Resolved'), ('SPAM_WARNING', 'Spam Warning'), ('STATUS_CHANGE', 'Status Change')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
