# Generated by Django 6.0.3 on 2026-03-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("REGISTERED_USER", "Registered User"),
                    ("INFRASTRUCTURE_AUTHORITY", "Infrastructure Authority"),
                    ("ADMINISTRATOR", "Administrator"),
                ],
                default="REGISTERED_USER",
                max_length=30,
            ),
        ),
    ]
