# Generated by Django 4.2.29 on 2026-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("UPVOTE", "Upvote"),
                            ("FLAG", "Flag"),
                            ("CONFIRM_RESOLUTION", "Confirm Resolution"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "interactions",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "photos",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BROKEN_RAMP", "Broken Ramp"),
                            ("NARROW_SIDEWALK", "Narrow Sidewalk"),
                            ("DAMAGED_SURFACE", "Damaged Surface"),
                            ("ROAD_CONSTRUCTION", "Road Construction"),
                            ("BLOCKED_PATH", "Blocked Path"),
                            ("OTHER", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("PASSIVE", "Passive"),
                            ("VERIFIED", "Verified"),
                            (
                                "RESOLVED_AWAITING_VALIDATION",
                                "Resolved Awaiting Validation",
                            ),
                            ("CLOSED", "Closed"),
                        ],
                        default="UNVERIFIED",
                        max_length=35,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="StatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("PASSIVE", "Passive"),
                            ("VERIFIED", "Verified"),
                            (
                                "RESOLVED_AWAITING_VALIDATION",
                                "Resolved Awaiting Validation",
                            ),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("PASSIVE", "Passive"),
                            ("VERIFIED", "Verified"),
                            (
                                "RESOLVED_AWAITING_VALIDATION",
                                "Resolved Awaiting Validation",
                            ),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=35,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "status_changes",
            },
        ),
    ]
