# Generated by Django 4.2.29 on 2026-04-06 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_is_indoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='context',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], default='OUTDOOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
